import geometryData from "./geometry.json";
import routesGeometryData from "./routes-geometry.json";
import type { CityGeometry, CityPack } from "../../types";

const geometry = geometryData as unknown as CityGeometry;

type RouteGeometryEntry = {
  relationRef?: string;
  lineName: string;
  operator: string;
  path: [number, number][];
  stops: { name: string; position: [number, number]; osmId?: string }[];
};

const routesGeometry = routesGeometryData as unknown as { generatedAt: string; routes: Record<string, RouteGeometryEntry> };

const metro52Path = routesGeometry.routes.metro_52.path;
const metro51Path = routesGeometry.routes.metro_51.path;
const tram4Path = routesGeometry.routes.tram_4.path;

/**
 * Amsterdam Centraal to RAI -- the real-geometry demo city pack for
 * RouteRoom 3D (ADR 0005, ADR 0006). Geometry is a one-time OpenStreetMap
 * export (see scripts/import-osm.mjs and ATTRIBUTION.md). Route options and
 * transit details are a curated snapshot, not live directions.
 */
export const amsterdamCity: CityPack = {
  id: "amsterdam_centrum_rai",
  name: "Amsterdam",
  district: "Centraal to RAI corridor",
  timezone: "Europe/Amsterdam",
  currency: "EUR",
  locale: "en-NL",
  description:
    "The corridor from Amsterdam Centraal to the RAI convention centre, built from a real OpenStreetMap export and a curated GVB transit snapshot.",
  attribution: [
    `© OpenStreetMap contributors, ODbL 1.0, exported ${geometry.source.exportedAt.slice(0, 10)}`,
    "Route times and fares are a curated snapshot, not live directions",
  ],

  geometry,

  landmarks: [
    {
      id: "centraal_station",
      name: "Amsterdam Centraal",
      kind: "origin",
      position: [4.9003, 52.3791],
      description: "Main rail hub where the demo trip begins.",
    },
    {
      id: "centraal_metro_platform",
      name: "Centraal metro entrance",
      kind: "entrance",
      position: [4.90075, 52.3781],
      description: "Step-free entrance beneath Centraal for the Noord/Zuidlijn (Metro 52 and 51).",
    },
    {
      id: "centraal_tram_stop",
      name: "Centraal tram stop",
      kind: "stop",
      position: [4.899, 52.3788],
      description: "Tram stop on Stationsplein outside Centraal.",
    },
    {
      id: "europaplein_station",
      name: "Europaplein",
      kind: "station",
      position: [4.8905, 52.3417],
      description: "Metro 52 station, lifts to street level.",
      osmId: "node/5737467956",
    },
    {
      id: "europaplein_tram_stop",
      name: "Europaplein tram stop",
      kind: "stop",
      position: [4.8912, 52.3413],
      description: "Tram stop on Europaboulevard near the Europaplein interchange.",
    },
    {
      id: "station_rai",
      name: "Station RAI",
      kind: "station",
      position: [4.8895, 52.3379],
      description: "Metro 50/51 and trains, step-free.",
    },
    {
      id: "station_rai_tram_stop",
      name: "Amsterdam, Station RAI (Drentepark)",
      kind: "stop",
      position: [4.8889, 52.3399],
      description: "Tram 4 terminus at the venue, on Drentepark.",
    },
    {
      id: "rai_main_entrance",
      name: "RAI main entrance",
      kind: "entrance",
      position: [4.8875, 52.3405],
      description: "Main entrance on Europaplein.",
    },
    {
      id: "rai_p1_entrance",
      name: "RAI entrance P1",
      kind: "entrance",
      position: [4.8872, 52.3394],
      description: "Pedestrian entrance P1 (Voetgangersingang RAI P1).",
    },
    {
      id: "rai_convention_centre",
      name: "RAI convention centre",
      kind: "venue",
      position: [4.888, 52.341],
      description: "Destination venue for the 08:30 event.",
    },
  ],

  trips: [
    {
      id: "trip_centraal_to_rai",
      name: "Centraal Station to RAI",
      description: "Morning trip from Amsterdam Centraal to the RAI convention centre for an 08:30 event.",
      originId: "centraal_station",
      destinationId: "rai_convention_centre",
      clockAt: "2026-09-04T07:25:00+02:00",
      departAt: "2026-09-04T07:45:00+02:00",
      arrivalDeadline: "2026-09-04T08:30:00+02:00",
      routeOptionIds: ["route_metro_52", "route_tram_4", "route_metro_51"],
    },
  ],
  defaultTripId: "trip_centraal_to_rai",

  routeOptions: [
    {
      id: "route_metro_52",
      name: "Metro 52 + walk from Europaplein",
      summary: "The fastest, step-free option, with the longest outdoor walk at the end.",
      currency: "EUR",
      durationMin: 19,
      durationTypical: 24,
      durationMax: 26,
      fareMin: 3.4,
      fareMax: 3.4,
      transfers: 0,
      walkingMeters: 490,
      reliability: "high",
      accessibility: "clear",
      confidence: 0.86,
      evidenceUpdatedAt: "2026-09-03T20:00:00+02:00",
      tradeoffs: ["Fastest", "Step-free with lifts", "Longest outdoor walk at the end"],
      segments: [
        {
          id: "seg_metro52_walk_to_platform",
          mode: "walk",
          label: "Walk to the Centraal metro entrance",
          fromLandmarkId: "centraal_station",
          toLandmarkId: "centraal_metro_platform",
          path: [
            [4.9003, 52.3791],
            [4.9007, 52.3786],
            [4.90075, 52.3781],
          ],
          durationMin: 2,
          durationMax: 3,
          distanceMeters: 118,
          fareMin: 0,
          fareMax: 0,
          reliability: "high",
          accessibility: "clear",
          rainExposure: "low",
          hasStairs: false,
          covered: true,
          notes: ["Covered concourse", "Step-free"],
        },
        {
          id: "seg_metro52_ride",
          mode: "metro",
          label: "Metro 52 to Europaplein",
          fromLandmarkId: "centraal_metro_platform",
          toLandmarkId: "europaplein_station",
          path: metro52Path,
          durationMin: 11,
          durationMax: 14,
          distanceMeters: 4482,
          fareMin: 3.4,
          fareMax: 3.4,
          reliability: "high",
          accessibility: "clear",
          rainExposure: "low",
          hasStairs: false,
          covered: true,
          lineName: "Metro 52",
          operator: "GVB",
          notes: ["Noord/Zuidlijn", "Step-free platforms"],
        },
        {
          id: "seg_metro52_walk_to_entrance",
          mode: "walk",
          label: "Walk from Europaplein to the RAI",
          fromLandmarkId: "europaplein_station",
          toLandmarkId: "rai_main_entrance",
          path: [
            [4.8905, 52.3417],
            [4.8899, 52.3423],
            [4.8882, 52.3417],
            [4.8872, 52.3409],
            [4.8875, 52.3405],
          ],
          durationMin: 5,
          durationMax: 8,
          distanceMeters: 372,
          fareMin: 0,
          fareMax: 0,
          reliability: "high",
          accessibility: "clear",
          rainExposure: "high",
          hasStairs: false,
          covered: false,
          notes: ["Uncovered the whole way", "Wide, clear pavement"],
        },
      ],
    },
    {
      id: "route_tram_4",
      name: "Tram 4 to the door",
      summary: "Stops right at the venue with the least walking, but slowest and traffic-sensitive.",
      currency: "EUR",
      durationMin: 31,
      durationTypical: 36,
      durationMax: 46,
      fareMin: 3.4,
      fareMax: 3.4,
      transfers: 0,
      walkingMeters: 219,
      reliability: "medium",
      accessibility: "clear",
      confidence: 0.74,
      evidenceUpdatedAt: "2026-09-03T20:00:00+02:00",
      tradeoffs: ["Stops right at the venue", "Least walking", "Slowest and traffic-sensitive"],
      segments: [
        {
          id: "seg_tram4_walk_to_stop",
          mode: "walk",
          label: "Walk to the Centraal tram stop",
          fromLandmarkId: "centraal_station",
          toLandmarkId: "centraal_tram_stop",
          path: [
            [4.9003, 52.3791],
            [4.8996, 52.3789],
            [4.899, 52.3788],
          ],
          durationMin: 2,
          durationMax: 3,
          distanceMeters: 94,
          fareMin: 0,
          fareMax: 0,
          reliability: "high",
          accessibility: "clear",
          rainExposure: "medium",
          hasStairs: false,
          covered: false,
          notes: ["Outdoor stop on Stationsplein"],
        },
        {
          id: "seg_tram4_ride",
          mode: "tram",
          label: "Tram 4 to Station RAI (Drentepark)",
          fromLandmarkId: "centraal_tram_stop",
          toLandmarkId: "station_rai_tram_stop",
          path: tram4Path,
          durationMin: 27,
          durationMax: 38,
          distanceMeters: 6066,
          fareMin: 3.4,
          fareMax: 3.4,
          reliability: "medium",
          accessibility: "clear",
          rainExposure: "medium",
          hasStairs: false,
          covered: false,
          lineName: "Tram 4",
          operator: "GVB",
          notes: ["Street-running tram, sensitive to road traffic", "Open-air platform"],
        },
        {
          id: "seg_tram4_walk_to_entrance",
          mode: "walk",
          label: "Walk from Drentepark to the RAI",
          fromLandmarkId: "station_rai_tram_stop",
          toLandmarkId: "rai_main_entrance",
          path: [
            [4.8889, 52.3399],
            [4.8882, 52.3403],
            [4.8875, 52.3405],
          ],
          durationMin: 2,
          durationMax: 4,
          distanceMeters: 125,
          fareMin: 0,
          fareMax: 0,
          reliability: "high",
          accessibility: "clear",
          rainExposure: "high",
          hasStairs: false,
          covered: false,
          notes: ["Uncovered", "Short walk direct to the entrance"],
        },
      ],
    },
    {
      id: "route_metro_51",
      name: "Metro 51 to Station RAI",
      summary: "Step-free with a short covered walk, slightly slower than the 52, arrives at the P1 side.",
      currency: "EUR",
      durationMin: 24,
      durationTypical: 29,
      durationMax: 42,
      fareMin: 3.4,
      fareMax: 3.4,
      transfers: 0,
      walkingMeters: 346,
      reliability: "high",
      accessibility: "clear",
      confidence: 0.8,
      evidenceUpdatedAt: "2026-09-03T20:00:00+02:00",
      tradeoffs: ["Step-free with a short covered walk", "Slightly slower than the 52", "Arrives at the P1 side"],
      segments: [
        {
          id: "seg_metro51_walk_to_platform",
          mode: "walk",
          label: "Walk to the Centraal metro entrance",
          fromLandmarkId: "centraal_station",
          toLandmarkId: "centraal_metro_platform",
          path: [
            [4.9003, 52.3791],
            [4.9007, 52.3786],
            [4.90075, 52.3781],
          ],
          durationMin: 2,
          durationMax: 3,
          distanceMeters: 118,
          fareMin: 0,
          fareMax: 0,
          reliability: "high",
          accessibility: "clear",
          rainExposure: "low",
          hasStairs: false,
          covered: true,
          notes: ["Covered concourse", "Step-free"],
        },
        {
          id: "seg_metro51_ride",
          mode: "metro",
          label: "Metro 51 to Station RAI",
          fromLandmarkId: "centraal_metro_platform",
          toLandmarkId: "station_rai",
          path: metro51Path,
          durationMin: 16,
          durationMax: 20,
          distanceMeters: 6220,
          fareMin: 3.4,
          fareMax: 3.4,
          reliability: "high",
          accessibility: "clear",
          rainExposure: "low",
          hasStairs: false,
          covered: true,
          lineName: "Metro 51",
          operator: "GVB",
          notes: ["Step-free platforms"],
        },
        {
          id: "seg_metro51_walk_to_entrance",
          mode: "walk",
          label: "Walk from Station RAI to entrance P1",
          fromLandmarkId: "station_rai",
          toLandmarkId: "rai_p1_entrance",
          path: [
            [4.8895, 52.3379],
            [4.8883, 52.3387],
            [4.8872, 52.3394],
          ],
          durationMin: 4,
          durationMax: 6,
          distanceMeters: 228,
          fareMin: 0,
          fareMax: 0,
          reliability: "high",
          accessibility: "clear",
          rainExposure: "medium",
          hasStairs: false,
          covered: false,
          notes: ["Partly covered walkway", "No stairs"],
        },
      ],
    },
  ],

  reports: [
    {
      id: "report_tram4_delay",
      segmentId: "seg_tram4_ride",
      category: "delay",
      text: "Tram 4 running 8 to 12 minutes late through Ferdinand Bolstraat during the morning peak because of road works.",
      observedAt: "2026-09-04T06:48:00+02:00",
      expiresAt: "2026-09-04T09:30:00+02:00",
      confidence: "medium",
      landmarkId: "station_rai_tram_stop",
      source: "seed",
    },
    {
      id: "report_europaplein_lift",
      segmentId: "seg_metro52_ride",
      category: "accessibility",
      text: "One of the two lifts at Europaplein is out of service; the other lift and the escalators are working.",
      observedAt: "2026-09-03T18:10:00+02:00",
      expiresAt: "2026-09-05T18:00:00+02:00",
      confidence: "low",
      landmarkId: "europaplein_station",
      source: "seed",
    },
  ],

  snapshot: {
    curatedAt: "2026-09-03",
    sources: ["GVB timetable and fare pages, consulted 2026-09-03", "OpenStreetMap route relations for Metro 52, Metro 51, Tram 4"],
    notes: [
      "Fares are the GVB standard 1-hour fare as understood on the curation date; verify before relying on them.",
      "Durations are typical scheduled ranges plus walking estimates; they are not live predictions.",
    ],
  },
};
