import type { CityPack } from "../types";

/**
 * Aurora City -- the primary demo city pack for RouteRoom 3D.
 *
 * Synthetic district: a west-side rail hub, a market square, a north transit
 * gate, and a riverside conference venue on the east bank. All data below is
 * invented for the demo and is not a real place.
 */
export const auroraCity: CityPack = {
  id: "demo_city",
  name: "Aurora City",
  district: "Riverside District",
  timezone: "Europe/Amsterdam",
  currency: "EUR",
  locale: "en-NL",
  description:
    "A synthetic riverside district built for the RouteRoom 3D demo, with a rail hub, a market square, and a conference venue across the river.",
  attribution: ["Synthetic demo data. Not a real city."],

  landmarks: [
    {
      id: "central_station",
      name: "Central Station",
      kind: "origin",
      position: [-4.8, 0.2, 2.8],
      description: "Main rail hub on the west edge of the district, where the demo trip begins.",
    },
    {
      id: "old_market",
      name: "Old Market",
      kind: "station",
      position: [-1.9, 0.2, 1.3],
      description: "Historic market square with a covered arcade and transit connections.",
    },
    {
      id: "north_gate",
      name: "North Gate",
      kind: "station",
      position: [2.2, 0.2, 2.2],
      description: "Northern transit gate linking the tram and metro lines to the riverside path.",
    },
    {
      id: "riverside_center",
      name: "Riverside Conference Center",
      kind: "venue",
      position: [4.7, 0.2, -2.7],
      description: "Conference venue on the east bank, the demo trip's destination.",
    },
    {
      id: "riverside_north_entrance",
      name: "Riverside Center North Entrance",
      kind: "entrance",
      position: [4.5, 0.2, -1.8],
      description: "Step-free entrance with a ramp on the north side",
    },
    {
      id: "river_crossing",
      name: "River Footbridge",
      kind: "crossing",
      position: [1.0, 0.2, -3.6],
      description: "Footbridge with stairs on the market side",
    },
    {
      id: "river_park",
      name: "River Park",
      kind: "park",
      position: [0, 0.2, -2.4],
    },
  ],

  sceneFeatures: [
    // Buildings
    { id: "foundry_tower", name: "Foundry Tower", kind: "building", position: [-4.6, 0, 1.8], size: [1.6, 2.2, 1.4], color: "#b5a389", roofColor: "#8c7b66" },
    { id: "gallery_hall", name: "Gallery Hall", kind: "building", position: [-4.6, 0, -2.0], size: [1.6, 1.4, 1.6], color: "#d2c4a8", roofColor: "#8c7b66" },
    { id: "market_hall", name: "Market Hall", kind: "building", position: [-2.4, 0, 1.8], size: [1.4, 1.4, 1.4], color: "#cbb894" },
    { id: "workshop_row", name: "Workshop Row", kind: "building", position: [-2.6, 0, -2.0], size: [1.6, 1.2, 1.4], color: "#9e9483" },
    { id: "civic_hall", name: "Civic Hall", kind: "building", position: [0.2, 0, 3.2], size: [1.8, 1.6, 1.8], color: "#b8a995" },
    { id: "depot", name: "Transit Depot", kind: "building", position: [0.2, 0, -2.0], size: [1.8, 1.0, 1.6], color: "#c3ad87" },
    { id: "museum", name: "City Museum", kind: "building", position: [3.2, 0, 2.0], size: [1.8, 1.8, 1.6], color: "#a69b86" },
    { id: "riverside_hall", name: "Riverside Hall", kind: "building", position: [3.2, 0, -2.4], size: [2.4, 1.6, 1.8], color: "#c3ad87", roofColor: "#8c7b66" },
    { id: "north_pavilion", name: "North Pavilion", kind: "building", position: [4.8, 0, 3.4], size: [1.4, 1.2, 1.4], color: "#b5a389" },
    { id: "east_lofts", name: "East Lofts", kind: "building", position: [5.2, 0, -2.4], size: [1.2, 1.4, 1.4], color: "#cbb894" },
    // Water, park, plaza
    { id: "river", name: "River", kind: "water", position: [0.7, -0.08, -4.2], size: [12, 0.08, 1.3], color: "#7fb0b5" },
    { id: "river_park_slab", name: "River Park", kind: "park", position: [0.1, -0.05, -2.3], size: [3.0, 0.1, 1.2], color: "#9cae85" },
    { id: "riverside_plaza", name: "Riverside Plaza", kind: "plaza", position: [4.4, -0.05, -2.9], size: [2.2, 0.05, 1.6], color: "#e0d8c4" },
    // Roads
    { id: "road_main_ew", name: "Market Way", kind: "road", position: [0, 0.02, 0.7], size: [12.5, 0.04, 0.6], color: "#b9b6a8" },
    { id: "road_ns_east", name: "Gate Street", kind: "road", position: [1.6, 0.02, 0], size: [0.6, 0.04, 10.5], color: "#b9b6a8" },
    { id: "road_ns_west", name: "Station Street", kind: "road", position: [-1.2, 0.02, 0], size: [0.6, 0.04, 10.5], color: "#b9b6a8" },
  ],

  routeOptions: [
    {
      id: "route_tram_walk",
      name: "Tram + shaded walk",
      summary: "One reliable transfer, short final walk with the best arrival buffer.",
      currency: "EUR",
      durationMin: 34,
      durationTypical: 41,
      durationMax: 49,
      fareMin: 4.5,
      fareMax: 6.0,
      transfers: 1,
      walkingMeters: 940,
      reliability: "high",
      accessibility: "clear",
      confidence: 0.88,
      evidenceUpdatedAt: "2026-09-04T06:22:00+02:00",
      tradeoffs: ["Costs a bit more than the bus", "Best arrival buffer", "One transfer"],
      primaryColor: "#d97757",
      segments: [
        {
          id: "seg_tram_walk_station_market",
          mode: "walk",
          label: "Walk to Old Market",
          fromLandmarkId: "central_station",
          toLandmarkId: "old_market",
          points: [
            [-4.8, 0.18, 2.8],
            [-3.2, 0.18, 2.0],
            [-1.9, 0.18, 1.3],
          ],
          durationMin: 7,
          durationMax: 10,
          distanceMeters: 420,
          fareMin: 0,
          fareMax: 0,
          reliability: "high",
          accessibility: "clear",
          rainExposure: "low",
          hasStairs: false,
          covered: true,
          notes: ["Mostly covered arcade", "No stairs"],
        },
        {
          id: "seg_tram_walk_market_gate",
          mode: "tram",
          label: "Tram 4 to North Gate",
          fromLandmarkId: "old_market",
          toLandmarkId: "north_gate",
          points: [
            [-1.9, 0.25, 1.3],
            [-1.2, 0.25, 0.9],
            [0.2, 0.25, 0.8],
            [1.6, 0.25, 1.2],
            [2.2, 0.25, 2.2],
          ],
          durationMin: 16,
          durationMax: 22,
          distanceMeters: 3100,
          fareMin: 4.5,
          fareMax: 6.0,
          reliability: "high",
          accessibility: "clear",
          rainExposure: "low",
          hasStairs: false,
          covered: true,
          lineName: "Tram 4",
          notes: ["Step-free platform", "Frequent service"],
        },
        {
          id: "seg_tram_walk_gate_entrance",
          mode: "walk",
          label: "Walk from North Gate",
          fromLandmarkId: "north_gate",
          toLandmarkId: "riverside_north_entrance",
          points: [
            [2.2, 0.18, 2.2],
            [3.4, 0.18, 0.2],
            [4.5, 0.18, -1.8],
          ],
          durationMin: 11,
          durationMax: 17,
          distanceMeters: 520,
          fareMin: 0,
          fareMax: 0,
          reliability: "high",
          accessibility: "clear",
          rainExposure: "low",
          hasStairs: false,
          covered: false,
          notes: ["Clear path along the museum side", "Wide entrance"],
        },
      ],
    },
    {
      id: "route_bus_market",
      name: "Express bus + river crossing",
      summary: "Fastest on a clear run, but the fare and travel time both swing more.",
      currency: "EUR",
      durationMin: 28,
      durationTypical: 38,
      durationMax: 60,
      fareMin: 1.8,
      fareMax: 2.5,
      transfers: 1,
      walkingMeters: 420,
      reliability: "medium",
      accessibility: "caution",
      confidence: 0.71,
      evidenceUpdatedAt: "2026-09-04T05:58:00+02:00",
      tradeoffs: ["Lowest fare", "Fastest on a clear run", "Stairs at the footbridge", "Exposed walking at both ends", "Active delay report"],
      primaryColor: "#5c8f9a",
      segments: [
        {
          id: "seg_bus_market_station_market",
          mode: "walk",
          label: "Walk to bus bay",
          fromLandmarkId: "central_station",
          toLandmarkId: "old_market",
          points: [
            [-4.8, 0.18, 2.8],
            [-3.0, 0.18, 1.8],
            [-1.9, 0.18, 1.3],
          ],
          durationMin: 4,
          durationMax: 6,
          distanceMeters: 220,
          fareMin: 0,
          fareMax: 0,
          reliability: "high",
          accessibility: "caution",
          rainExposure: "high",
          hasStairs: false,
          covered: false,
          notes: ["Two curb crossings", "Outdoor queue at the bus bay"],
        },
        {
          id: "seg_bus_market_market_crossing",
          mode: "bus",
          label: "Express 12 to the river crossing",
          fromLandmarkId: "old_market",
          toLandmarkId: "river_crossing",
          points: [
            [-1.9, 0.25, 1.3],
            [-1.2, 0.25, 0.2],
            [0.2, 0.25, -1.5],
            [1.0, 0.25, -3.6],
          ],
          durationMin: 20,
          durationMax: 49,
          distanceMeters: 3900,
          fareMin: 1.8,
          fareMax: 2.5,
          reliability: "medium",
          accessibility: "caution",
          rainExposure: "medium",
          hasStairs: false,
          covered: false,
          lineName: "Express 12",
          notes: ["Road delay reported on south loop"],
        },
        {
          id: "seg_bus_market_crossing_center",
          mode: "walk",
          label: "Walk over the footbridge",
          fromLandmarkId: "river_crossing",
          toLandmarkId: "riverside_center",
          points: [
            [1.0, 0.18, -3.6],
            [2.8, 0.18, -3.1],
            [4.7, 0.18, -2.7],
          ],
          durationMin: 3,
          durationMax: 5,
          distanceMeters: 200,
          fareMin: 0,
          fareMax: 0,
          reliability: "high",
          accessibility: "caution",
          rainExposure: "high",
          hasStairs: true,
          covered: false,
          notes: ["Stairs on the market side of the footbridge", "Fully outdoor"],
        },
      ],
    },
    {
      id: "route_step_free",
      name: "Step-free metro route",
      summary: "Most accessible option, with a longer platform transfer.",
      currency: "EUR",
      durationMin: 43,
      durationTypical: 50,
      durationMax: 58,
      fareMin: 5.0,
      fareMax: 6.5,
      transfers: 2,
      walkingMeters: 380,
      reliability: "high",
      accessibility: "clear",
      confidence: 0.82,
      evidenceUpdatedAt: "2026-09-04T05:40:00+02:00",
      tradeoffs: ["Fewest walking meters", "Two transfers", "Longest typical duration"],
      primaryColor: "#8c6bb1",
      segments: [
        {
          id: "seg_step_free_station_market",
          mode: "metro",
          label: "Metro M1 to Old Market",
          fromLandmarkId: "central_station",
          toLandmarkId: "old_market",
          points: [
            [-4.8, 0.25, 2.8],
            [-3.2, 0.25, 2.0],
            [-1.9, 0.25, 1.3],
          ],
          durationMin: 17,
          durationMax: 22,
          distanceMeters: 3500,
          fareMin: 5.0,
          fareMax: 6.5,
          reliability: "high",
          accessibility: "clear",
          rainExposure: "low",
          hasStairs: false,
          covered: true,
          lineName: "M1",
          notes: ["Elevators at both stations"],
        },
        {
          id: "seg_step_free_market_gate",
          mode: "metro",
          label: "Metro M2 to North Gate",
          fromLandmarkId: "old_market",
          toLandmarkId: "north_gate",
          points: [
            [-1.9, 0.25, 1.3],
            [-0.2, 0.25, 1.9],
            [1.6, 0.25, 2.0],
            [2.2, 0.25, 2.2],
          ],
          durationMin: 12,
          durationMax: 17,
          distanceMeters: 2400,
          fareMin: 0,
          fareMax: 0,
          reliability: "high",
          accessibility: "clear",
          rainExposure: "low",
          hasStairs: false,
          covered: true,
          lineName: "M2",
          notes: ["Long but step-free platform connection"],
        },
        {
          id: "seg_step_free_gate_entrance",
          mode: "walk",
          label: "Step-free path to the entrance",
          fromLandmarkId: "north_gate",
          toLandmarkId: "riverside_north_entrance",
          points: [
            [2.2, 0.18, 2.2],
            [3.4, 0.18, 0.2],
            [4.5, 0.18, -1.8],
          ],
          durationMin: 14,
          durationMax: 19,
          distanceMeters: 380,
          fareMin: 0,
          fareMax: 0,
          reliability: "high",
          accessibility: "clear",
          rainExposure: "medium",
          hasStairs: false,
          covered: false,
          notes: ["Ramp access", "Avoids stairs"],
        },
      ],
    },
  ],

  reports: [
    {
      id: "report_bus_delay",
      segmentId: "seg_bus_market_market_crossing",
      category: "delay",
      text: "South loop has been running 10 to 15 minutes late during the morning peak.",
      observedAt: "2026-09-04T05:58:00+02:00",
      expiresAt: "2026-09-04T08:00:00+02:00",
      confidence: "medium",
      landmarkId: "old_market",
      source: "seed",
    },
    {
      id: "report_footbridge_stairs",
      segmentId: "seg_bus_market_crossing_center",
      category: "accessibility",
      text: "Temporary works narrow the footbridge steps on the market side.",
      observedAt: "2026-09-03T17:30:00+02:00",
      expiresAt: "2026-09-05T18:00:00+02:00",
      confidence: "low",
      landmarkId: "river_crossing",
      source: "seed",
    },
  ],

  defaultTrip: {
    originId: "central_station",
    destinationId: "riverside_center",
    clockAt: "2026-09-04T06:40:00+02:00",
    departAt: "2026-09-04T07:05:00+02:00",
    arrivalDeadline: "2026-09-04T08:30:00+02:00",
  },
};
