import type { CityPack } from "../types";

/**
 * Harbor City -- a second, smaller demo city pack for RouteRoom 3D.
 *
 * Synthetic district: a ferry terminal on the west shore, a quay station, and
 * a maritime hall venue on the east shore, split by a harbor channel. All
 * data below is invented for the demo and is not a real place.
 */
export const harborCity: CityPack = {
  id: "harbor_city",
  name: "Harbor City",
  district: "Old Port",
  timezone: "Asia/Singapore",
  currency: "SGD",
  locale: "en-SG",
  description:
    "A synthetic port district built for the RouteRoom 3D demo, with a ferry terminal, a quay station, and a maritime hall across the harbor channel.",
  attribution: ["Synthetic demo data. Not a real city."],

  landmarks: [
    {
      id: "ferry_terminal",
      name: "Ferry Terminal",
      kind: "origin",
      position: [-5.0, 0.2, -1.5],
      description: "West-shore ferry terminal where the demo trip begins.",
    },
    {
      id: "quay_station",
      name: "Quay Station",
      kind: "station",
      position: [-1.5, 0.2, 0.5],
      description: "Transit station on the quay, linking ferry, bus, and walking routes.",
    },
    {
      id: "maritime_hall",
      name: "Maritime Hall",
      kind: "venue",
      position: [4.5, 0.2, 1.0],
      description: "Event hall on the east shore, the demo trip's destination.",
    },
    {
      id: "maritime_hall_entrance",
      name: "Maritime Hall Entrance",
      kind: "entrance",
      position: [4.0, 0.2, 2.0],
      description: "Step-free entrance facing the plaza on the north side.",
    },
    {
      id: "harbor_bridge",
      name: "Harbor Bridge",
      kind: "crossing",
      position: [1.5, 0.2, -2.0],
      description: "Pedestrian bridge over the harbor channel, with stairs at both ends.",
    },
  ],

  sceneFeatures: [
    // Buildings
    { id: "quay_warehouse", name: "Quay Warehouse", kind: "building", position: [-3.5, 0, 2.0], size: [1.8, 1.6, 1.4], color: "#b5a389", roofColor: "#8c7b66" },
    { id: "customs_house", name: "Customs House", kind: "building", position: [-3.5, 0, -2.2], size: [1.6, 1.4, 1.4], color: "#cbb894" },
    { id: "spice_market", name: "Spice Market", kind: "building", position: [0.5, 0, 2.2], size: [2.0, 1.4, 1.6], color: "#a69b86" },
    { id: "maritime_hall_building", name: "Maritime Hall", kind: "building", position: [4.2, 0, 1.2], size: [2.4, 1.8, 1.8], color: "#c3ad87", roofColor: "#8c7b66" },
    { id: "harbor_offices", name: "Harbor Offices", kind: "building", position: [2.0, 0, -2.0], size: [1.6, 1.2, 1.4], color: "#b8a995" },
    { id: "north_pier_building", name: "North Pier Building", kind: "building", position: [-0.5, 0, 3.5], size: [1.4, 1.2, 1.4], color: "#9e9483" },
    // Water, park
    { id: "harbor_water", name: "Harbor Channel", kind: "water", position: [0, -0.08, -4.0], size: [13, 0.08, 1.5], color: "#7fb0b5" },
    { id: "quay_green", name: "Quay Green", kind: "park", position: [-2.5, -0.05, 3.0], size: [2.4, 0.1, 1.6], color: "#9cae85" },
    // Roads
    { id: "road_main_ew", name: "Shore Road", kind: "road", position: [0, 0.02, 0.0], size: [12.5, 0.04, 0.6], color: "#b9b6a8" },
    { id: "road_ns_quay", name: "Quay Street", kind: "road", position: [-1.5, 0.02, 1.5], size: [0.6, 0.04, 7], color: "#b9b6a8" },
  ],

  routeOptions: [
    {
      id: "route_ferry_direct",
      name: "Ferry + waterfront walk",
      summary: "Fastest option, timed to a fixed ferry schedule.",
      currency: "SGD",
      durationMin: 16,
      durationTypical: 20,
      durationMax: 24,
      fareMin: 3.5,
      fareMax: 4.5,
      transfers: 1,
      walkingMeters: 300,
      reliability: "high",
      accessibility: "clear",
      confidence: 0.85,
      evidenceUpdatedAt: "2026-09-04T06:50:00+08:00",
      tradeoffs: ["Fastest of the three options", "Ferry runs on a fixed schedule", "One transfer"],
      primaryColor: "#d97757",
      segments: [
        {
          id: "seg_ferry_direct_terminal_quay",
          mode: "walk",
          label: "Walk to Quay Station",
          fromLandmarkId: "ferry_terminal",
          toLandmarkId: "quay_station",
          points: [
            [-5.0, 0.18, -1.5],
            [-3.2, 0.18, -0.6],
            [-1.5, 0.18, 0.5],
          ],
          durationMin: 4,
          durationMax: 6,
          distanceMeters: 300,
          fareMin: 0,
          fareMax: 0,
          reliability: "high",
          accessibility: "clear",
          rainExposure: "low",
          hasStairs: false,
          covered: false,
          notes: ["Flat waterfront path"],
        },
        {
          id: "seg_ferry_direct_quay_entrance",
          mode: "ferry",
          label: "Harbor Shuttle to Maritime Hall",
          fromLandmarkId: "quay_station",
          toLandmarkId: "maritime_hall_entrance",
          points: [
            [-1.5, 0.25, 0.5],
            [0.8, 0.25, -1.0],
            [2.6, 0.25, 0.2],
            [4.0, 0.25, 2.0],
          ],
          durationMin: 12,
          durationMax: 18,
          distanceMeters: 2600,
          fareMin: 3.5,
          fareMax: 4.5,
          reliability: "high",
          accessibility: "clear",
          rainExposure: "low",
          hasStairs: false,
          covered: true,
          lineName: "Harbor Shuttle",
          notes: ["Runs every 20 minutes", "Covered deck seating"],
        },
      ],
    },
    {
      id: "route_walk_bridge",
      name: "Walk over the harbor bridge",
      summary: "No fare, fully on foot, but fully exposed to the weather.",
      currency: "SGD",
      durationMin: 21,
      durationTypical: 25,
      durationMax: 29,
      fareMin: 0,
      fareMax: 0,
      transfers: 0,
      walkingMeters: 1550,
      reliability: "high",
      accessibility: "caution",
      confidence: 0.9,
      evidenceUpdatedAt: "2026-09-04T06:50:00+08:00",
      tradeoffs: ["No fare", "Fully outdoor and exposed to weather", "Stairs at the harbor bridge", "No transfers"],
      primaryColor: "#5c8f9a",
      segments: [
        {
          id: "seg_walk_bridge_terminal_bridge",
          mode: "walk",
          label: "Walk to Harbor Bridge",
          fromLandmarkId: "ferry_terminal",
          toLandmarkId: "harbor_bridge",
          points: [
            [-5.0, 0.18, -1.5],
            [-2.0, 0.18, -1.8],
            [1.5, 0.18, -2.0],
          ],
          durationMin: 12,
          durationMax: 16,
          distanceMeters: 900,
          fareMin: 0,
          fareMax: 0,
          reliability: "high",
          accessibility: "clear",
          rainExposure: "high",
          hasStairs: false,
          covered: false,
          notes: ["Flat shore road, fully outdoor"],
        },
        {
          id: "seg_walk_bridge_bridge_entrance",
          mode: "walk",
          label: "Cross Harbor Bridge to the entrance",
          fromLandmarkId: "harbor_bridge",
          toLandmarkId: "maritime_hall_entrance",
          points: [
            [1.5, 0.18, -2.0],
            [2.8, 0.18, 0.0],
            [4.0, 0.18, 2.0],
          ],
          durationMin: 9,
          durationMax: 13,
          distanceMeters: 650,
          fareMin: 0,
          fareMax: 0,
          reliability: "high",
          accessibility: "caution",
          rainExposure: "high",
          hasStairs: true,
          covered: false,
          notes: ["Stairs at both ends of the bridge", "Fully outdoor"],
        },
      ],
    },
    {
      id: "route_bus_bridge",
      name: "Bus + bridge crossing",
      summary: "Cheapest transit option, timing depends on the bus.",
      currency: "SGD",
      durationMin: 23,
      durationTypical: 29,
      durationMax: 39,
      fareMin: 1.5,
      fareMax: 2.5,
      transfers: 1,
      walkingMeters: 950,
      reliability: "medium",
      accessibility: "caution",
      confidence: 0.68,
      evidenceUpdatedAt: "2026-09-04T06:45:00+08:00",
      tradeoffs: ["Cheapest transit option", "Bus timing can vary", "Stairs at the harbor bridge"],
      primaryColor: "#8c6bb1",
      segments: [
        {
          id: "seg_bus_bridge_terminal_quay",
          mode: "walk",
          label: "Walk to Quay Station",
          fromLandmarkId: "ferry_terminal",
          toLandmarkId: "quay_station",
          points: [
            [-5.0, 0.18, -1.5],
            [-3.2, 0.18, -0.6],
            [-1.5, 0.18, 0.5],
          ],
          durationMin: 4,
          durationMax: 6,
          distanceMeters: 300,
          fareMin: 0,
          fareMax: 0,
          reliability: "high",
          accessibility: "clear",
          rainExposure: "low",
          hasStairs: false,
          covered: false,
          notes: ["Flat waterfront path"],
        },
        {
          id: "seg_bus_bridge_quay_bridge",
          mode: "bus",
          label: "Harbor Line 2 to the bridge",
          fromLandmarkId: "quay_station",
          toLandmarkId: "harbor_bridge",
          points: [
            [-1.5, 0.25, 0.5],
            [-0.2, 0.25, -0.8],
            [1.5, 0.25, -2.0],
          ],
          durationMin: 10,
          durationMax: 20,
          distanceMeters: 2400,
          fareMin: 1.5,
          fareMax: 2.5,
          reliability: "medium",
          accessibility: "caution",
          rainExposure: "medium",
          hasStairs: false,
          covered: false,
          lineName: "Harbor Line 2",
          notes: ["Running about 8 minutes behind schedule this morning"],
        },
        {
          id: "seg_bus_bridge_bridge_entrance",
          mode: "walk",
          label: "Cross Harbor Bridge to the entrance",
          fromLandmarkId: "harbor_bridge",
          toLandmarkId: "maritime_hall_entrance",
          points: [
            [1.5, 0.18, -2.0],
            [2.8, 0.18, 0.0],
            [4.0, 0.18, 2.0],
          ],
          durationMin: 9,
          durationMax: 13,
          distanceMeters: 650,
          fareMin: 0,
          fareMax: 0,
          reliability: "high",
          accessibility: "caution",
          rainExposure: "high",
          hasStairs: true,
          covered: false,
          notes: ["Stairs at both ends of the bridge", "Fully outdoor"],
        },
      ],
    },
  ],

  reports: [
    {
      id: "report_harbor_bus_delay",
      segmentId: "seg_bus_bridge_quay_bridge",
      category: "delay",
      text: "Harbor Line 2 has been running about 8 minutes behind schedule this morning.",
      observedAt: "2026-09-04T06:45:00+08:00",
      expiresAt: "2026-09-04T09:00:00+08:00",
      confidence: "medium",
      landmarkId: "quay_station",
      source: "seed",
    },
  ],

  defaultTrip: {
    originId: "ferry_terminal",
    destinationId: "maritime_hall",
    clockAt: "2026-09-04T07:10:00+08:00",
    departAt: "2026-09-04T07:30:00+08:00",
    arrivalDeadline: "2026-09-04T08:45:00+08:00",
  },
};
